# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: <blog>
brand-title: Arun's Blog
email: arunv4700@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! This will mainly be used to talk about things I learn day to day as a developer, as well other things like travel, cars, life in general. Feel free to subscribe if any of this content resonates with you!
baseurl: "" # the subpath of your site, e.g. /blog
linkurl: "http://avarghese.me/blog" # the subpath of your site, e.g. /blog
url: http://avarghese.me # the base hostname & protocol for your site
website: http://avarghese.me
github_username:  vararun
linkedin_username: varghesearun
facebook_username: avarghese1
instagram_username: var_arun
behance_username: avarghese
dribbble_username: avarghese
codepen_username: avarghese
youtube_username: vararun
date_format: "%Y, %B %-d"
# Build settings
markdown: kramdown
exclude: ["node_modules"]